name: Deploy To S3 And Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # uses - 라이브러리
      # uses: actions/checkout@v4 - GitHub Actions에서 리포지토리의 코드를 체크아웃(다운로드)하기 위해 사용하는 액션
      # uses: actions/checkout@v4 - 이 단계는 워크플로우의 첫 번째 단계에서 주로 사용
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: 의존성 설치
        run: npm i

      - name: 빌드하기
        run: npm run build

      - name: AWS Resource에 접근할 수 있게 AWS 인증 설정
        uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: ap-northeast-2
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}

      - name: S3 기존 파일들 전체 삭제
        # rm - remove
        # recursive - 지정한 S3 버킷 또는 경로 내의 모든 객체를 재귀적으로 삭제
        run: |
          aws s3 rm --recursive s3://ok-armstorong

      # - name: Defugging
      #   run: |
      #     ls
      #     echo "-----------------"
      #     cd dist
      #     ls

#
#
#
#
#
# # Workflow
# name: Github Actions 실행시켜보기

# on: # 할 때 마다
#   push: # 푸시
#     branches: # 브랜치에
#       - main # main이라는

# # on, push, branches 문법 의미
# # main이라는 브랜치에 push를 할 때 마다 작업을 실행 시키겠다.

# jobs: # Workflow는 여러개의 Job으로 이루어질 수 있다.
#   My-Deploy-Job:
#     runs-on: ubuntu-latest # ubuntu라는 운영체제를 가장 최근 버전으로 사용하겠다.
#     # ubuntu - 운영체제중 하나
#     # latest - 가장 최근 버전

#     steps: # 하나의 Job은 여러개의 Step으로 이루어져있다.
#       - name: Hello World 출력하기 # 이름
#         run: echo "Hello World" # 어떤 명령어를 실행시킬 것인가

#       - name: 여러 명령어 문장 작성하기
#         # pwd - 현재 경로 출력
#         run: |
#           echo "Good"
#           echo "Morning"
#           pwd

#       - name: Github Actions 자체 저장되어 있는 변수 사용해보기
#         # echo $GITHUB_REPOSITORY - 현재 레포지토리의 이름(이미 운영체제에 저장되어있는 변수)
#         # echo $GITHUB_SHA - 커밋의 고유 아이디 값(이미 운영체제에 저장되어있는 변수)
#         run: |
#           echo $GITHUB_REPOSITORY
#           echo $GITHUB_SHA

#       - name: Github Actions Secret 변수 사용해보기2
#         run: |
#           echo ${{ secrets.MY_NAME }}
#           echo ${{ secrets.MY_HOBBY }}
